// Generated by CoffeeScript 1.6.3
(function() {
  var mainLoop;

  window.onload = function() {
    var clickTimer, longPress,
      _this = this;
    window.board = new Board("board");
    window.buttons = new Interface("buttons");
    window.board.addMirror({
      x: 600,
      y: 70
    }, Math.PI / 4);
    window.board.addMirror({
      x: 200,
      y: 70
    }, -Math.PI / 4);
    window.board.addMirror({
      x: 400,
      y: 70
    }, 0);
    window.board.addMirror({
      x: 200,
      y: 600 - 70
    }, Math.PI + Math.PI / 4);
    window.board.addMirror({
      x: 600,
      y: 600 - 70
    }, Geometry.rad(135));
    window.board.addMirror({
      x: 400,
      y: 600 - 70
    }, Geometry.rad(90));
    window.board.addMirror({
      x: 700,
      y: 300
    }, Geometry.rad(45));
    window.board.addWall({
      x: 100,
      y: 300
    }, Geometry.rad(270), 100);
    window.board.addStar({
      x: 200,
      y: 350
    }, 10);
    window.board.addStar({
      x: 100,
      y: 450
    }, 10);
    window.board.animate();
    clickTimer = false;
    longPress = false;
    document.addEventListener('mousedown', function(e) {
      var pos;
      pos = {
        x: e.pageX - board.canvas.offsetLeft,
        y: e.pageY - board.canvas.offsetTop
      };
      return clickTimer = setTimeout(function() {
        var a;
        longPress = true;
        a = board.collided(pos);
        console.log(a);
        if (a && a.turnable) {
          return buttons.turner = new Turner(a);
        }
      }, 1000);
    });
    document.addEventListener('mouseup', function(e) {
      var pos;
      pos = {
        x: e.pageX - board.canvas.offsetLeft,
        y: e.pageY - board.canvas.offsetTop
      };
      buttons.turner = null;
      clearTimeout(clickTimer);
      if (!longPress) {
        if (!board.selectGun(pos)) {
          board.shot(pos);
        }
      }
      return longPress = false;
    });
    document.addEventListener('mousemove', function(e) {
      var pos;
      pos = {
        x: e.pageX - board.canvas.offsetLeft,
        y: e.pageY - board.canvas.offsetTop
      };
      if (longPress) {
        return buttons.pointTo(pos);
      }
    });
    return requestAnimationFrame(mainLoop);
  };

  mainLoop = function() {
    var fps;
    if (typeof mainLoop.lastTime === 'undefined') {
      mainLoop.lastTime = new Date().getTime();
    } else {
      fps = 1000 / (new Date().getTime() - mainLoop.lastTime);
      document.getElementById("fps").innerHTML = fps.toFixed(2) + ' fps';
      mainLoop.lastTime = new Date().getTime();
    }
    board.draw();
    buttons.draw();
    return requestAnimationFrame(mainLoop);
  };

  window.requestAnimationFrame = (function() {
    return window.requestAnimationFrame || window.webkitrequestAnimationFrame || window.mozrequestAnimationFrame || function(cback) {
      return window.setTimeout(cback, 1000 / 60);
    };
  })();

}).call(this);
