// Generated by CoffeeScript 1.6.3
(function() {
  var ang, canvas, context, mainLoop;

  canvas = null;

  context = null;

  ang = 0;

  window.onload = function() {
    canvas = document.getElementById("board");
    context = canvas.getContext("2d");
    return requestAnimationFrame(mainLoop);
  };

  mainLoop = function() {
    canvas.width = canvas.width;
    drawer.rect(context, "fill", ang, {
      x: 400,
      y: 300
    }, 100, 100);
    ang++;
    return requestAnimationFrame(mainLoop);
  };

  window.requestAnimationFrame = (function() {
    return window.requestAnimationFrame || window.webkitrequestAnimationFrame || window.mozrequestAnimationFrame || function(cback) {
      return window.setTimeout(cback, 1000 / 60);
    };
  })();

}).call(this);
