// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module('Mirror');

  Mirror.Plane = (function(_super) {
    __extends(Plane, _super);

    Plane.prototype.type = "Mirror";

    Plane.prototype.height = 10;

    function Plane(pos, angle, width, turnable) {
      if (pos == null) {
        pos = {
          x: 0,
          y: 0
        };
      }
      this.angle = angle != null ? angle : 0;
      this.width = width != null ? width : 100;
      this.turnable = turnable != null ? turnable : true;
      Plane.__super__.constructor.call(this, pos, this.angle, this.width, this.height);
    }

    Plane.prototype.reflect = function(ang) {
      return Geometry.reduceAngle(2 * this.angle - ang);
    };

    Plane.prototype.draw = function(context) {
      drawer.rectangle(context, "stroke", this.angle, this.position, this.width, this.height, {
        color: 'white',
        shadow: {
          color: '#fff',
          offsetX: 0,
          offsetY: 0,
          blur: 10
        }
      });
      return drawer.distance(context, this.angle, this.position, 100, {
        color: 'white'
      });
    };

    return Plane;

  })(Geometry.Rectangle);

}).call(this);
