// Generated by CoffeeScript 1.6.3
(function() {
  var Star, Wall, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Wall = (function(_super) {
    __extends(Wall, _super);

    function Wall() {
      _ref = Wall.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Wall.prototype.type = "Wall";

    Wall.prototype.turnable = false;

    return Wall;

  })(Geometry.Rectangle);

  Star = (function() {
    Star.prototype.radius = 10;

    Star.prototype.position = null;

    Star.prototype.glow = false;

    Star.prototype.type = "Star";

    Star.prototype.color = "#fff";

    Star.prototype.stage = 0;

    Star.prototype.stageMod = 1;

    function Star(pos, radius) {
      if (pos == null) {
        pos = {
          x: 0,
          y: 0
        };
      }
      this.radius = radius != null ? radius : 1;
      this.position = {
        x: pos.x,
        y: pos.y
      };
      this.stage = ~~(Math.random() * 50);
    }

    Star.prototype.collided = function(point) {
      return Geometry.dist2(this.position, point) <= this.radius * this.radius;
    };

    Star.prototype.draw = function(context) {
      var a, shadow;
      if (this.stage > 50 || this.stage < 0) {
        this.stageMod *= -1;
      }
      this.stage += this.stageMod;
      a = "stroke";
      shadow = {
        color: this.color,
        offsetX: 0,
        offsetY: 0,
        blur: 10
      };
      if (this.glow === true) {
        a = "fill";
        shadow.color = '#aaeeff';
        shadow.offsetX = 0;
        shadow.offsetY = 0;
        shadow.blur = this.stage / 2;
      }
      return drawer.arc(context, a, this.position, 0, 360, this.radius, {
        color: this.color,
        shadow: shadow
      });
    };

    return Star;

  })();

  window.Star = Star;

  window.Wall = Wall;

}).call(this);
